import React from 'react';
import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {render,screen,fireEvent,cleanup,within,waitFor} from '@testing-library/react';
import fs from 'node:fs';
vi.mock('../src/scene.js',()=>({createScene:vi.fn((el,{onReady})=>{onReady();return{selectCity:vi.fn(),setMotion:vi.fn(),setDayRoute:vi.fn(),rotate:vi.fn(),reset:vi.fn(),setViewMode:vi.fn(),dispose:vi.fn()}})}));
import App from '../src/App.jsx';
import {createScene} from '../src/scene.js';
const data=JSON.parse(fs.readFileSync('public/data/official-route.json')),media=JSON.parse(fs.readFileSync('public/data/attraction-media.json')),food=JSON.parse(fs.readFileSync('public/data/food-guide.json')),xhs=JSON.parse(fs.readFileSync('public/data/xiaohongshu.json'));
beforeEach(()=>{localStorage.clear();global.fetch=vi.fn(url=>Promise.resolve({ok:true,json:()=>Promise.resolve(String(url).includes('food-guide')?food:String(url).includes('xiaohongshu')?xhs:String(url).includes('attraction-media')?media:data)}))});afterEach(cleanup);
async function ready(guide=false){render(<App/>);await screen.findByRole('heading',{name:'是时候去看海了。'});await waitFor(()=>expect(createScene.mock.results.at(-1)?.value).toBeDefined());if(guide)fireEvent.click(screen.getByRole('button',{name:'查看全部',exact:true}));}
function begin(){fireEvent.click(screen.getByRole('button',{name:'开始旅程',exact:true}))}
function day(i){fireEvent.click(screen.getAllByRole('tab')[i])}
function stage(name){fireEvent.click(within(screen.getByRole('group',{name:'当天浏览步骤'})).getByRole('button',{name:new RegExp(name)}))}
function tools(){const s=screen.getByText('视角与地图工具',{selector:'summary'});if(!s.closest('details').open)fireEvent.click(s);return within(s.closest('details'));}
function resource(name){fireEvent.click(screen.getByRole('button',{name:'打开旅行资料'}));fireEvent.click(within(screen.getByRole('navigation',{name:'旅行资料'})).getByRole('button',{name,exact:true}));}
function visible(el){expect(el.closest('[hidden]')).toBeNull();let p=el.parentElement;while(p){if(p.tagName==='DETAILS')expect(p.open).toBe(true);p=p.parentElement;}return el;}
function zhanqiao(){const card=screen.getByRole('button',{name:/栈桥 · 回澜阁 查看实景与攻略/}).closest('article');fireEvent.click(within(card).getByRole('button',{name:/查看实景与攻略/}));return within(card);}

it('starts with one clear entry and keeps every content library out of the initial view',async()=>{await ready();expect(screen.getAllByRole('button',{name:'开始旅程',exact:true})).toHaveLength(1);expect(screen.queryByRole('tab')).toBeNull();expect(screen.queryByRole('region',{name:'城市实拍图库'})).toBeNull();expect(screen.queryByRole('region',{name:'按城市查看美食图文库'})).toBeNull();expect(screen.queryByRole('article',{name:/行程安排/})).toBeNull();expect(createScene.mock.calls.at(-1)[1].viewMode).toBe('overview');});
it('the guided path goes roadbook, attractions, food and next day, with no forced selection',async()=>{await ready();begin();expect(createScene.mock.results.at(-1).value.setViewMode).toHaveBeenLastCalledWith('immersive');for(let i=0;i<6;i++){expect(visible(screen.getByRole('article',{name:`第 ${i+1} 天行程安排`}))).toBeTruthy();expect(screen.queryByRole('region',{name:/景点卡/})).toBeNull();expect(screen.queryByRole('region',{name:'按城市查看美食图文库'})).toBeNull();fireEvent.click(screen.getByRole('button',{name:'挑选景点',exact:true}));expect(visible(screen.getByRole('region',{name:/景点卡/}))).toBeTruthy();expect(screen.queryByRole('article',{name:/行程安排/})).toBeNull();fireEvent.click(screen.getByRole('button',{name:'看看当地美食',exact:true}));expect(visible(screen.getByRole('region',{name:'按城市查看美食图文库'}))).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:i===5?'完成旅程预览':`继续第 ${i+2} 天`,exact:true}));}expect(screen.getByRole('heading',{name:'旅程预览完成'})).toBeTruthy();expect(JSON.parse(localStorage.getItem('coastal-journal-v1')).stamps).toEqual([]);fireEvent.click(screen.getByRole('button',{name:'返回最后一天'}));expect(screen.getByRole('group',{name:'当天浏览步骤'})).toBeTruthy();});
it('switching dates keeps the destination, route car and visible contents together',async()=>{await ready();begin();tools().getByRole('button',{name:'切换 2D'}).click();day(1);expect(screen.getByLabelText('小车位于青岛')).toBeTruthy();expect(screen.getByRole('article',{name:'第 2 天行程安排'}).textContent).toContain('连云港 → 青岛');fireEvent.click(screen.getByRole('button',{name:'地图城市：威海'}));expect(screen.getAllByRole('tab')[2].getAttribute('aria-selected')).toBe('true');expect(screen.getByRole('article',{name:'第 3 天行程安排'})).toBeTruthy();day(3);fireEvent.click(screen.getByRole('button',{name:'地图城市：威海'}));expect(screen.getAllByRole('tab')[3].getAttribute('aria-selected')).toBe('true');});
it('camera overview, rotation and reset do not restart the day or browsing step',async()=>{await ready();begin();day(1);stage('想去哪里');const t=tools();fireEvent.click(t.getByRole('button',{name:'查看全程'}));expect(screen.getByRole('region',{name:'青岛景点卡'})).toBeTruthy();expect(screen.getAllByRole('tab')[1].getAttribute('aria-selected')).toBe('true');fireEvent.click(t.getByRole('button',{name:'向左旋转地图'}));fireEvent.click(t.getByRole('button',{name:'重置三维视角'}));const scene=createScene.mock.results.at(-1).value;expect(scene.rotate).toHaveBeenCalledWith(-1);expect(scene.reset).toHaveBeenCalled();fireEvent.click(t.getByRole('button',{name:'近看城市',exact:true}));expect(scene.setViewMode).toHaveBeenLastCalledWith('immersive');});
it('reference views return to the same date and stage, without changing camera mode',async()=>{await ready();begin();day(1);stage('想去哪里');const card=zhanqiao();fireEvent.click(card.getByRole('button',{name:/加入 10.03 自选/}));resource('城市实拍');expect(visible(screen.getByRole('region',{name:'城市实拍图库'}))).toBeTruthy();expect(screen.queryByRole('region',{name:'青岛景点卡'})).toBeNull();fireEvent.click(screen.getByRole('button',{name:'返回旅程 · 第 2 天'}));expect(screen.getByRole('combobox',{name:'栈桥 · 回澜阁停留分钟'})).toBeTruthy();expect(screen.getByRole('heading',{name:'第 2 天 · 想去哪里'})).toBeTruthy();expect(createScene.mock.results.at(-1).value.setViewMode).toHaveBeenLastCalledWith('immersive');});
it('mode switching preserves expanded attraction, picks and stamps, and unfolds full reference information',async()=>{await ready();begin();day(1);stage('想去哪里');const card=zhanqiao();fireEvent.click(card.getByRole('button',{name:/加入 10.03 自选/}));fireEvent.change(screen.getByRole('combobox',{name:'栈桥 · 回澜阁停留分钟'}),{target:{value:'120'}});fireEvent.click(screen.getByRole('button',{name:'收藏这一站的章'}));fireEvent.click(screen.getByRole('button',{name:'查看全部',exact:true}));expect(visible(screen.getByRole('article',{name:'第 2 天行程安排'}))).toBeTruthy();expect(visible(screen.getByRole('region',{name:'青岛景点卡'}))).toBeTruthy();expect(screen.getByRole('region',{name:'城市实拍图库'})).toBeTruthy();expect(screen.getByRole('region',{name:'按城市查看美食图文库'})).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'按天看行程',exact:true}));expect(screen.getByRole('heading',{name:'第 2 天 · 想去哪里'})).toBeTruthy();expect(screen.getByRole('combobox',{name:'栈桥 · 回澜阁停留分钟'}).value).toBe('120');expect(screen.getByRole('button',{name:'已盖章 · 点按撤回'})).toBeTruthy();});
it('five and six day personal plans stay separate; last day clamps safely when shortening',async()=>{await ready();begin();day(1);stage('想去哪里');fireEvent.click(zhanqiao().getByRole('button',{name:/加入 10.03 自选/}));fireEvent.click(screen.getByRole('button',{name:'5 天',exact:true}));expect(document.querySelector('.pick-total').textContent).toContain('0');fireEvent.click(screen.getByRole('button',{name:/^6 天/}));expect(document.querySelector('.pick-total').textContent).toContain('60');fireEvent.click(screen.getByRole('button',{name:'移除栈桥 · 回澜阁'}));expect(document.querySelector('.pick-total').textContent).toContain('0');day(5);fireEvent.click(screen.getByRole('button',{name:'5 天',exact:true}));expect(screen.getAllByRole('tab')).toHaveLength(5);expect(screen.getByRole('article',{name:'第 5 天行程安排'}).textContent).toContain('日照 → 芜湖');});
it('keyboard day navigation reaches the final and first day',async()=>{await ready();begin();fireEvent.keyDown(screen.getAllByRole('tab')[0],{key:'End'});expect(screen.getAllByRole('tab')[5].getAttribute('aria-selected')).toBe('true');fireEvent.keyDown(screen.getAllByRole('tab')[5],{key:'Home'});expect(screen.getAllByRole('tab')[0].getAttribute('aria-selected')).toBe('true');});
it('rain fallback is reversible and does not change the itinerary',async()=>{await ready();begin();fireEvent.click(screen.getByRole('button',{name:'雨天 / 大风怎么改'}));expect(screen.getByText('保留城市，减少户外')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'收起雨天方案'}));expect(screen.queryByText('保留城市，减少户外')).toBeNull();expect(screen.getAllByRole('tab')).toHaveLength(6);});
it('menu Escape restores focus and resources can be accessed before starting',async()=>{await ready();const button=screen.getByRole('button',{name:'打开旅行资料'});fireEvent.click(button);fireEvent.keyDown(document,{key:'Escape'});expect(button.getAttribute('aria-expanded')).toBe('false');expect(document.activeElement).toBe(button);resource('美食图文');expect(visible(screen.getByRole('region',{name:'按城市查看美食图文库'}))).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'返回全程预览'}));expect(screen.getByRole('button',{name:'开始旅程',exact:true})).toBeTruthy();});
it('budget and checklist remain usable in preparation and preserve changes on return',async()=>{await ready();resource('出发准备');expect(screen.getByText('¥ 9,160')).toBeTruthy();fireEvent.change(screen.getByRole('spinbutton',{name:'每间每晚房价 元'}),{target:{value:'500'}});expect(screen.getByText('¥ 9,660')).toBeTruthy();const box=screen.getByRole('checkbox',{name:'轮胎、灯光、雨刷与油液检查'});fireEvent.click(box);expect(screen.getByText('1 / 6 项准备好了')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'返回全程预览'}));resource('出发准备');expect(screen.getByRole('checkbox',{name:'轮胎、灯光、雨刷与油液检查'}).checked).toBe(true);});
it('source search, filters and reset work in the dedicated source view',async()=>{await ready();resource('资料库');fireEvent.change(screen.getByRole('combobox',{name:'按城市筛选来源'}),{target:{value:'威海'}});fireEvent.change(screen.getByRole('searchbox'),{target:{value:'不存在的地名xyz'}});expect(screen.getByText('这组筛选还没有条目')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'清空筛选'}));expect(screen.getByRole('combobox',{name:'按城市筛选来源'}).value).toBe('全部');expect(screen.getByRole('searchbox').value).toBe('');});
it('WebGL failure offers a working route that synchronizes selected city to a day',async()=>{vi.mocked(createScene).mockReturnValueOnce(null);render(<App/>);await screen.findByRole('heading',{name:'是时候去看海了。'});await screen.findByLabelText('可点击的二维跨城路线示意图');begin();fireEvent.click(screen.getByRole('button',{name:'地图城市：威海'}));expect(screen.getByRole('article',{name:'第 3 天行程安排'})).toBeTruthy();expect(tools().getByRole('button',{name:'2D 模式'}).disabled).toBe(true);});
it('system reduced motion disables the animation switch honestly',async()=>{const mq=vi.spyOn(window,'matchMedia').mockImplementation(()=>({matches:true,addEventListener(){},removeEventListener(){}}));try{await ready();expect(tools().getByRole('button',{name:'遵循系统减少动态设置'}).disabled).toBe(true);}finally{mq.mockRestore()}});
it('attraction original source and author remain available with honest link status',async()=>{await ready();begin();day(1);stage('想去哪里');const card=zhanqiao(),a=media.attractions.find(a=>a.id==='qd_zhanqiao');expect(card.getByRole('img').getAttribute('src')).toContain('assets/places/');expect(card.getByRole('link',{name:/照片原帖：青岛栈桥/}).getAttribute('href')).toBe(a.private_reference_images[0].source_url);expect(card.getByRole('link',{name:/畅🌈 · 小红书/})).toBeTruthy();expect(card.getAllByText(/App/).length).toBeGreaterThan(0);});
it('stamps survive a remount and invalid journal storage is ignored',async()=>{await ready();begin();stage('想去哪里');fireEvent.click(screen.getByRole('button',{name:'收藏这一站的章'}));cleanup();render(<App/>);await screen.findByRole('heading',{name:'是时候去看海了。'});begin();stage('想去哪里');expect(screen.getByRole('button',{name:'已盖章 · 点按撤回'})).toBeTruthy();cleanup();localStorage.setItem('coastal-journal-v1',JSON.stringify({stamps:['wrong','wuhu','wuhu'],plans:{bad:{test:9999}}}));render(<App/>);await screen.findByRole('heading',{name:'是时候去看海了。'});expect(JSON.parse(localStorage.getItem('coastal-journal-v1')).stamps).toEqual(['wuhu']);expect(JSON.parse(localStorage.getItem('coastal-journal-v1')).plans).toEqual({});});
it('Huaian comparison cannot be added as a default itinerary stop or stamped',async()=>{await ready();begin();stage('想去哪里');const summary=screen.getByText('浏览其他城市与途中备选',{selector:'summary'});fireEvent.click(summary);fireEvent.click(screen.getByRole('button',{name:'淮安 · 备选'}));const region=within(screen.getByRole('region',{name:'淮安景点卡'}));expect(region.queryByRole('button',{name:'收藏这一站的章'})).toBeNull();fireEvent.click(region.getByRole('button',{name:/御码头 查看实景与攻略/}));expect(region.getByRole('button',{name:/加入 10.02 自选/}).disabled).toBe(true);});
it('motion pause remains reversible and current resources pause the scene',async()=>{await ready();begin();const t=tools();fireEvent.click(t.getByRole('button',{name:'暂停三维动态'}));expect(t.getByRole('button',{name:'开启三维动态'})).toBeTruthy();fireEvent.click(t.getByRole('button',{name:'开启三维动态'}));resource('城市实拍');expect(createScene.mock.results.at(-1).value.setMotion).toHaveBeenLastCalledWith(false);fireEvent.click(screen.getByRole('button',{name:'返回旅程 · 第 1 天'}));expect(createScene.mock.results.at(-1).value.setMotion).toHaveBeenLastCalledWith(true);});

it('opening a resource from full guide mode displays just that resource and returns without resetting mode',async()=>{await ready(true);resource('城市实拍');expect(screen.getByRole('region',{name:'城市实拍图库'})).toBeTruthy();expect(screen.queryByRole('checkbox',{name:'轮胎、灯光、雨刷与油液检查'})).toBeNull();expect(screen.queryByRole('searchbox')).toBeNull();expect(screen.queryByRole('article',{name:/行程安排/})).toBeNull();fireEvent.click(screen.getByRole('button',{name:'返回全程预览'}));expect(screen.getByRole('button',{name:'查看全部',exact:true}).getAttribute('aria-pressed')).toBe('true');expect(screen.getByRole('article',{name:'第 1 天行程安排'})).toBeTruthy();});

it('switching day sections and dates does not request a page scroll',async()=>{
 await ready();begin();await waitFor(()=>expect(document.activeElement?.id).toBe('journey-stage-title'));
 Element.prototype.scrollIntoView.mockClear();
 stage('想去哪里');await new Promise(resolve=>setTimeout(resolve,40));
 stage('今日安排');await new Promise(resolve=>setTimeout(resolve,40));
 day(1);await new Promise(resolve=>setTimeout(resolve,40));
 expect(Element.prototype.scrollIntoView).not.toHaveBeenCalled();
 expect(screen.getByRole('article',{name:'第 2 天行程安排'})).toBeTruthy();
});

it('homepage city photograph opens that city day instead of silently changing a hidden map',async()=>{await ready();fireEvent.click(screen.getByRole('button',{name:'看看青岛的行程'}));expect(screen.getByRole('heading',{name:'第 2 天 · 今日安排'})).toBeTruthy();expect(screen.getAllByRole('tab')[1].getAttribute('aria-selected')).toBe('true');});
