// CPU geometry / scene API smoke test. This does not claim WebGL visual quality.
import fs from 'node:fs';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import * as RealThree from 'three';
const dom=new JSDOM('<div id="root"></div>');globalThis.window=dom.window;globalThis.document=dom.window.document;
let callbackId=0;const callbacks=new Map();globalThis.requestAnimationFrame=fn=>{callbacks.set(++callbackId,fn);return callbackId};globalThis.cancelAnimationFrame=id=>callbacks.delete(id);
globalThis.ResizeObserver=class{observe(){}disconnect(){}};globalThis.IntersectionObserver=class{observe(){}disconnect(){}};
let lastScene,lastCamera;
class FakeRenderer{constructor(){this.domElement=document.createElement('canvas');this.shadowMap={};this.info={render:{triangles:0}}}setClearColor(){}setPixelRatio(){}setSize(){}dispose(){}render(s,c){lastScene=s;lastCamera=c;c.updateMatrixWorld();s.updateMatrixWorld();let triangles=0;s.traverse(o=>{if(o.isMesh){const p=o.geometry.getAttribute('position');assert.ok(p);for(const n of p.array)assert.ok(Number.isFinite(n));triangles+=(o.geometry.index?.count||p.count)/3;}assert.ok(o.position.toArray().every(Number.isFinite))});this.info.render.triangles=triangles;}}
globalThis.__SMOKE_THREE__={...RealThree,WebGLRenderer:FakeRenderer};
const source=fs.readFileSync('src/scene.js','utf8').replace("import * as THREE from 'three';","const THREE=globalThis.__SMOKE_THREE__;");
const temp='src/.scene-smoke-temp.mjs';fs.writeFileSync(temp,source);
try{const {createScene}=await import('../'+temp+'?t='+Date.now());for(const [width,height] of [[330,348],[360,370],[400,370],[1280,530]]){const root=document.getElementById('root');root.getBoundingClientRect=()=>({width,height,left:0,top:0});const s=createScene(root,{reducedMotion:true});for(const city of ['wuhu','huaian','lianyungang','qingdao','weihai','rizhao','wuhu']){s.selectCity(city);s.setDayRoute('wuhu',city);assert.equal(root.querySelectorAll('button[data-selected="true"]').length,1);s.rotate(1);s.rotate(-1);}s.setDayRoute('wuhu','weihai');assert.ok(lastScene.getObjectByName('route-car').position.z < -4);s.setDayRoute('weihai','rizhao');assert.ok(lastScene.getObjectByName('route-car').position.z > 2);assert.equal(lastScene.getObjectByName('day-route-highlight').children.length,3);assert.equal(lastScene.getObjectByName('route-car').scale.x,.9);s.reset();assert.equal(root.querySelectorAll('.coastal-city-tag').length,6);let meshes=0,triangles=0;const bounds={minX:Infinity,maxX:-Infinity,minY:Infinity,maxY:-Infinity};lastScene.traverse(o=>{if(o.isMesh){meshes++;if(o.material.type!=='ShadowMaterial'){const p=o.geometry.attributes.position;for(let i=0;i<p.count;i++){const v=new RealThree.Vector3().fromBufferAttribute(p,i).applyMatrix4(o.matrixWorld).project(lastCamera);bounds.minX=Math.min(bounds.minX,v.x);bounds.maxX=Math.max(bounds.maxX,v.x);bounds.minY=Math.min(bounds.minY,v.y);bounds.maxY=Math.max(bounds.maxY,v.y);}}triangles+=(o.geometry.index?.count||o.geometry.attributes.position.count)/3}});assert.ok(bounds.minX>=-1&&bounds.maxX<=1&&bounds.minY>=-1&&bounds.maxY<=1);console.log(JSON.stringify({width,height,meshes,triangles,finiteGeometry:true,projectedBounds:bounds,cameraBounds:[lastCamera.left,lastCamera.right,lastCamera.top,lastCamera.bottom]}));s.dispose();assert.equal(root.childElementCount,0);callbacks.clear();}}
finally{fs.rmSync(temp,{force:true});delete globalThis.__SMOKE_THREE__;}
