import React,{useEffect,useState} from 'react';
import {ArrowUpRight,MapPin,Plus,Minus,Check,Stamp,ImageSquare,Clock,Warning,Copy} from '@phosphor-icons/react';
import {safeExternal} from './utils.js';
import GettyPhoto from './GettyPhoto.jsx';
const B=import.meta.env.BASE_URL;
const featuredIds=new Set(['lyg_democracy_road','lyg_yanhe_lane','qd_zhanqiao','qd_zhongshan_road','qd_mayfour_square','wh_happiness_gate','wh_banyue_bay','wh_maotou_hill','wh_international_beach','rz_wanpingkou','rz_lighthouse','wh_zhongjiang_pagoda']);
const licensedImage=a=>a.images?.find(i=>i.reuse_status==='explicitly_licensed'&&i.visual_verified&&i.url);
const privateImage=a=>a.private_reference_images?.find(i=>i.reuse_status==='private_personal_reference'&&i.visual_verified&&i.url);
const roleLabels={first_night_optional:'到得早再逛',default_short_walk:'行程内的散步点',optional_on_route:'顺路可选',replaces_old_town:'替换老城，不叠加',optional_near_hotel:'离住宿近才去',deprioritized_candidate:'有空再去',excluded_default_candidate:'这次不安排',interest_and_opening_conditional:'喜欢且正常营业再去',default_north_coast:'北部海岸：步行或乘车',arrival_optional_near_hotel:'抵达后顺路可选',optional_second_area:'精力允许再换片区',whole_day_replacement:'占用整日，替换北线',east_route_optional:'东线顺路可选',meal_area_near_hotel_only:'只选住宿附近餐区',unconfirmed_rain_candidate:'营业情况还没确认',return_night_optional:'返程早到才逛',visual_landmark_only:'地图地标，非新增安排',stopover_comparison_only:'途中备选，非默认安排'};
function Link({href,children}){return safeExternal(href)?<a href={href} target="_blank" rel="noopener noreferrer">{children}<ArrowUpRight size={13}/></a>:<span>{children}</span>}
function readStore(){try{const x=JSON.parse(localStorage.getItem('coastal-journal-v1')||'{}');const plans={};for(const [key,val] of Object.entries(x.plans||{})){if(!/^[56]-2026-10-0[2-7]$/.test(key)||!val||typeof val!=='object')continue;plans[key]=Object.fromEntries(Object.entries(val).filter(([id,n])=>/^[a-z0-9_]+$/.test(id)&&[30,60,90,120,180,240].includes(n)));}return{plans,stamps:[...new Set(Array.isArray(x.stamps)?x.stamps.filter(v=>['wuhu','lianyungang','qingdao','weihai','rizhao'].includes(v)):[])]}}catch{return{plans:{},stamps:[]}}}
export default function AttractionDeck({media,city:routeCity,day,days,activeDay,data,onChooseDay,onCity,itinerary,guided=false}){
 const [alternateCity,setAlternateCity]=useState(false);
 const city=alternateCity?{id:'huaian',name:'淮安',en:'HUAIAN',tag:'途中备选',desc:'这些地点供途中停靠比较，不自动加入当前行程。'}:routeCity;
 const [journal,setJournal]=useState(readStore),[storageFailed,setStorageFailed]=useState(false),[copied,setCopied]=useState(''),[openId,setOpenId]=useState(''),[showCandidates,setShowCandidates]=useState(false);
 useEffect(()=>{try{localStorage.setItem('coastal-journal-v1',JSON.stringify(journal));setStorageFailed(false)}catch{setStorageFailed(true)}},[journal]);
 useEffect(()=>{setAlternateCity(false)},[routeCity.id]);
 useEffect(()=>{setOpenId('');setShowCandidates(false)},[city.id]);
 const attractions=(media.attractions||[]).filter(a=>a.city===city.name);
 const shown=showCandidates||alternateCity?attractions:attractions.filter(a=>featuredIds.has(a.id));const candidateCount=alternateCity?0:attractions.length-attractions.filter(a=>featuredIds.has(a.id)).length;const synthesis=data.city_synthesis?.[city.name];
 const featured=(media.attractions||[]).filter(a=>featuredIds.has(a.id));const featuredPhotoCount=featured.filter(a=>!privateImage(a)&&licensedImage(a)).length;
 const all=media.attractions||[];const allPhotos=all.filter(a=>a.images?.some(i=>i.reuse_status==='explicitly_licensed'&&i.visual_verified&&i.url)).length;const allPosts=all.filter(a=>a.xhs_notes?.some(n=>n.dedicated_topic_verified&&(n.dedicated_scenery_post||n.topic_kind==='food'))).length;
 const privatePhotos=all.filter(a=>privateImage(a)).length;const featuredPrivate=featured.filter(a=>privateImage(a)).length;const featuredMissing=featured.filter(a=>!privateImage(a)&&!licensedImage(a)).length;
 const planKey=`${days}-${day.date}`,picks=journal.plans[planKey]||{};
 const picked=Object.entries(picks).map(([id,minutes])=>({spot:(media.attractions||[]).find(a=>a.id===id),minutes})).filter(x=>x.spot);
 const total=picked.reduce((n,x)=>n+x.minutes,0);const stamped=journal.stamps.includes(city.id);
 function toggle(a){setJournal(j=>{const p={...(j.plans[planKey]||{})};if(p[a.id])delete p[a.id];else p[a.id]=60;return{...j,plans:{...j.plans,[planKey]:p}}})}
 function minutes(id,v){setJournal(j=>({...j,plans:{...j.plans,[planKey]:{...(j.plans[planKey]||{}),[id]:Number(v)}}}))}
 async function copy(n){try{await navigator.clipboard.writeText(n.copy_fallback||`${n.title} ${n.author}`);setCopied(n.note_id)}catch{setCopied(`failed-${n.note_id}`)}}
 const matchingDay=itinerary.days.findIndex(d=>d.sleep===city.name);
 const cityTabs=<div className="deck-city-tabs" role="group" aria-label="按城市查看景点照片">{[{id:'wuhu',name:'芜湖'},{id:'lianyungang',name:'连云港'},{id:'qingdao',name:'青岛'},{id:'weihai',name:'威海'},{id:'rizhao',name:'日照'},{id:'huaian',name:'淮安'}].map(c=><button key={c.id} aria-pressed={city.id===c.id} onClick={()=>{setAlternateCity(c.id==='huaian');if(c.id!=='huaian')onCity?.(c.id)}}>{c.name}{c.id==='huaian'?' · 备选':''}</button>)}</div>;
 const photoCoverage=<>{featured.length>0&&<p className="small muted">精选 {featured.length} 个地点中，{featuredPhotoCount} 个已有站内许可实景图，{featuredPrivate} 个已有小红书私人参考图，{featuredMissing} 个请打开原帖 / 来源页看实景。占位图标不是现场照片；全站其他许可照片还包含研究候选。</p>}<p className="small muted">全量 {all.length} 张景点卡：{privatePhotos} 张已有小红书私人参考图，{all.length-privatePhotos} 张仍待补小红书图片；另有 {allPhotos} 张许可实景图，{allPosts} 张有景点或餐区专帖。许可照片并非小红书下载图；所有署名与缺口保留。</p></>;
 function noteContent(n,primary=false){return <div className="dedicated-note" key={n.note_id}><small>{n.dedicated_scenery_post?'景点专门攻略':n.topic_kind==='food'?'街区餐饮专门攻略':'仅停车 / 交通主题，景观专帖仍待补'}</small>{!primary&&<><Link href={n.url}>{n.title}</Link><p>作者：{n.author}</p></>}<p>{n.date_visible||'页面未显示日期'} · {n.link_status_label||'此入口尚未重验，可能需 App / 登录；可按标题与作者在小红书搜索'}</p>{n.body_summary&&<p>{n.body_summary}</p>}{!primary&&<><button className="secondary" onClick={()=>copy(n)}><Copy size={15}/>{copied===n.note_id?'标题已复制':'复制标题与作者'}</button>{copied===`failed-${n.note_id}`&&<p role="status">剪贴板不可用，请手动复制上方文字</p>}</>}<details className="note-verification"><summary>原帖查看说明</summary>{n.current_body_read_verified===true&&<p className="small muted">本次已阅读正文{n.link_checked_at?`（${n.link_checked_at.slice(0,10)}）`:''}。</p>}<p className="small muted">{n.link_status_label||'此入口尚未重验，可能需 App / 登录；可按标题与作者在小红书搜索。'}</p>{(n.anonymous_access_verified===false||n.mobile_link_verified===false)&&<p className="small muted">{n.anonymous_access_verified===false&&n.mobile_link_verified===false?'匿名及手机打开未验证':n.anonymous_access_verified===false?'匿名打开未验证':'手机打开未验证'}。</p>}</details></div>}

 return <section id="city-attractions" className="attraction-deck" aria-label={`${city.name}景点卡`}>
  <div className="deck-heading"><div><p className="eyebrow">{city.en} / 打开这一站</p><h2>{city.name}<span>{city.tag}</span></h2><p>{city.desc}</p></div>{!alternateCity&&<button className={`stamp-button ${stamped?'stamped':''}`} aria-pressed={stamped} onClick={()=>setJournal(j=>({...j,stamps:stamped?j.stamps.filter(x=>x!==city.id):[...j.stamps,city.id]}))}><Stamp size={24}/><span>{stamped?'已盖章 · 点按撤回':'收藏这一站的章'}</span></button>}</div>
  <p className="deck-hint">{guided?'先点照片看详情；喜欢的地点可加入当天自选，最后再继续下一天。':'点卡片展开实景、出处和专门攻略。盖章仅作手账收藏，不记录定位，也不要求完成所有景点。'}</p>
  {guided?<details className="deck-browse"><summary>浏览其他城市与途中备选</summary>{cityTabs}</details>:cityTabs}
  {guided?<details className="deck-photo-info"><summary>照片与出处说明</summary>{photoCoverage}</details>:photoCoverage}
  {!attractions.length&&<p className="media-empty">这一站的景点资料仍在核验，原路线与行程安排可继续使用。</p>}
  {synthesis&&<details className="stopover-evidence"><summary>这一晚，为什么这样停<Plus size={17}/></summary><p>{synthesis.main_line}</p><p>{synthesis.why}</p><p className="missing-source"><Warning size={16}/>{synthesis.when_tired_or_rain}</p><p>住宿区域：{synthesis.sleep_area}</p><p>{synthesis.next_morning}</p><p className="small">{synthesis.quality_note}</p><div className="source-refs">{synthesis.sources.map(n=><Link href={n.url} key={n.url}>{n.author} · {n.title}</Link>)}</div></details>}
  <div className="deck-scope"><p>{alternateCity?'途中备选地点，仅供停靠比较，不自动加入行程':showCandidates?'更多候选与替代安排；请按当天时间取舍':'精选看点 · 留时间给喜欢的地方'}</p>{candidateCount>0&&<button className="secondary" aria-expanded={showCandidates} onClick={()=>setShowCandidates(v=>!v)}>{showCandidates?'收起更多地点':`再看 ${candidateCount} 处地点`}{showCandidates?<Minus size={15}/>:<Plus size={15}/>}</button>}</div>
  <div className="spot-cards">{shown.map(a=>{const im=privateImage(a)||licensedImage(a);const privateRef=im?.reuse_status==='private_personal_reference';const notes=a.xhs_notes||[];const scenic=notes.some(n=>n.dedicated_topic_verified&&(n.dedicated_scenery_post||n.topic_kind==='food'));const isPlaceNote=n=>n.dedicated_topic_verified&&(n.dedicated_scenery_post||n.topic_kind==='food');const primaryNote=privateRef?notes.find(n=>n.note_id===im.note_id):notes.find(n=>n.note_id===a.preferred_note_id&&isPlaceNote(n))||notes.find(isPlaceNote);const wrongCity=day.sleep!==a.city;const locked=['excluded_default_candidate','visual_landmark_only','stopover_comparison_only','unconfirmed_rain_candidate'].includes(a.route_role);return <article className={`spot-card ${openId===a.id?'expanded':''}`} key={a.id}>
   <button className="spot-cover" aria-expanded={openId===a.id} aria-controls={`spot-${a.id}`} onClick={()=>setOpenId(openId===a.id?'':a.id)}>{im?<img src={`${B}${im.url}`} alt={im.alt} width={im.width} height={im.height} loading="lazy" decoding="async"/>:<span className="photo-pending"><ImageSquare size={30}/><span>{a.embeds?.length?'实景图请打开来源':'实景图片待核'}</span><small>{a.embeds?.length?'非现场照片 · 打开来源查看':'占位图标，非现场照片'}</small></span>}<span className="spot-cover-title"><strong>{a.name}</strong><small>{openId===a.id?'收起详情':'查看实景与攻略'}<Plus size={16}/></small></span></button>
   {primaryNote&&<div className="original-photo-link"><Link href={primaryNote.url}>{privateRef?`照片原帖：${primaryNote.title}`:`地点原帖：${primaryNote.title}`}</Link><small>作者：{primaryNote.author}</small><small>{primaryNote.link_status_label||'此入口尚未重验，可能需 App / 登录'}</small><button className="text-button" onClick={()=>copy(primaryNote)}><Copy size={14}/>{copied===primaryNote.note_id?'标题已复制':'复制标题与作者'}</button>{copied===`failed-${primaryNote.note_id}`&&<small role="status">请手动复制上方标题与作者</small>}</div>}
   <span className="role-chip">{roleLabels[a.route_role]||'可选候选'}</span>
   {im&&<p className="photo-credit"><Link href={im.source_url}>{im.author} · {im.source_name||'实景摄影'}</Link>{privateRef?<span>私人旅行参考 · 未取得公开转载许可</span>:<Link href={im.license_url}>{im.license}</Link>}<span>{im.attribution}</span><span>{im.capture_year?`${im.capture_year} 年影像`:'拍摄年份未明'} · 不能据此判断当前客流</span></p>}
   <div id={`spot-${a.id}`} hidden={openId!==a.id} className="spot-expanded"><p>{a.description||im?.caption||`${a.name}是${city.name}的一个候选看点。是否前往取决于当天时段、天气和停车条件。`}</p>{im&&<p className="small muted">{im.source_label}<br/>{im.changes}</p>}
    {(openId===a.id?(a.embeds||[]).slice(0,1):[]).map(item=><GettyPhoto key={item.asset_id} item={item}/>)}
    {primaryNote&&noteContent(primaryNote,true)}
    {notes.some(n=>n.note_id!==primaryNote?.note_id)&&<details className="other-notes"><summary>其他参考帖</summary>{notes.filter(n=>n.note_id!==primaryNote?.note_id).map(n=>noteContent(n))}</details>}
    {!scenic&&<p className="missing-source"><Clock size={15}/>该景点专门介绍帖仍待核，城市综合攻略不充数</p>}
    <div className="spot-actions"><button className="secondary" disabled={wrongCity||locked} aria-pressed={!!picks[a.id]} onClick={()=>toggle(a)}>{picks[a.id]?<Minus size={16}/>:<Plus size={16}/>} {picks[a.id]?'从当天自选移除':`加入 ${day.date.slice(5).replace('-','.')} 自选`}</button>{wrongCity&&matchingDay>=0&&<button className="text-button" onClick={()=>onChooseDay(matchingDay)}>切到 {city.name} 当天</button>}</div>
    {locked&&<p className="small">此项当前未满足纳入条件，不自动追加到当天路线</p>}{a.route_role==='whole_day_replacement'&&<p className="missing-source"><Warning size={15}/>这是整日替代线，请同时移除北线自选；不能把两条线塞在同一天</p>}
   </div>
  </article>})}</div>
  <div className="day-picks"><div><p className="eyebrow">MY LITTLE PLAN / 当天自选</p><h3>{day.date.slice(5).replace('-','.')} · 停留时间自己定</h3><p>你选的景点会单独保存，不会修改原行程。每处默认 60 分钟只是可编辑的个人预算，不是推荐游玩时长。</p></div><strong className="pick-total">{total}<small>分钟 · 计划游玩</small></strong>
   {!picked.length?<p className="picks-empty">先点景点卡，再加入当天。什么都不加，也是一份好行程。</p>:<div className="picked-list">{picked.map(({spot,minutes:m})=><label key={spot.id}><span>{spot.name}</span><select value={m} aria-label={`${spot.name}停留分钟`} onChange={e=>minutes(spot.id,e.target.value)}>{[30,60,90,120,180,240].map(v=><option key={v} value={v}>{v} 分钟</option>)}</select><button aria-label={`移除${spot.name}`} onClick={()=>toggle(spot)}><Minus size={18}/></button></label>)}</div>}
   <p className="drive-delta"><MapPin size={17}/><span><strong>绕路要多长时间：待实时导航核算。</strong>停车入口、酒店位置和国庆拥堵未确定，不显示虚构的“多开几分钟”。已在原行程中的点不要把停留时间重复相加，休息与返程缓冲不能压缩。</span></p>{total>180&&<p className="missing-source"><Warning size={17}/>自选已超过 3 小时；换城市的当天请优先删点，勿用晚到或疲劳驾驶补时间</p>}
   <p className="small muted">印章是可选收藏，什么都不加、不盖章，也可以继续下一天。</p>
   <p className="storage-note">{storageFailed?'本设备禁止存储，选择只在当前页面有效':'自选和印章仅保存在当前浏览器，可随时移除；5 / 6 天分别保存'} · 已收集 {journal.stamps.length} / 5 城印章</p>
  </div>
 </section>
}
