import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Heart,X,ArrowLeft,ArrowRight,ArrowCounterClockwise,MapPin,ForkKnife,Download,ArrowUpRight,Check,Compass} from '@phosphor-icons/react';
import {COLLECTION_KEY,CITY_ORDER,makeCards,makeRoute,readChoices,routeStops} from './collection-model.js';
import {safeExternal} from './utils.js';
import './card-collections.css';
const B=import.meta.env.BASE_URL;
const cityLines={'芜湖':'江风作序，从这里出发','连云港':'山海相逢，先歇一晚','青岛':'红瓦与海，收藏老城风景','威海':'安静的海，慢慢地喜欢','日照':'把回程，留给一片海','淮安':'途中备选，运河边的烟火'};
const kindLabel=c=>c.kind==='spot'?'景点':'美食';
function SourceLink({href,children}){return safeExternal(href)?<a href={href} target="_blank" rel="noopener noreferrer">{children}<ArrowUpRight size={15}/></a>:null}
function Photo({card,className=''}){const[failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[card?.photo?.url]);return card?.photo?.url&&!failed?<img className={className} src={B+card.photo.url} alt={`${card.name} · 原帖实拍`} loading="lazy" draggable="false" onError={()=>setFailed(true)}/>:<div className={`cc-no-photo ${className}`}><Compass size={34}/><span>实景图暂未载入</span></div>}
function Details({card,onClose}){
 const ref=useRef(null);useEffect(()=>{const d=ref.current;if(d.showModal)d.showModal();else d.setAttribute('open','');return()=>{d.close?.()}},[]);
 const r=card.raw;return <dialog className="cc-dialog" ref={ref} aria-label={`${card.name}详情`} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose()}}><div className="cc-dialog-inner"><button className="cc-close" aria-label="关闭详情" onClick={onClose}><X size={24}/></button><Photo card={card}/><div className="cc-detail-body"><span className="cc-eyebrow">{card.city} / {kindLabel(card)}</span><h2>{card.name}</h2><p>{card.summary}</p>{card.warning&&<p className="cc-warning">{card.warning}</p>}{card.kind==='food'&&<><h3>这一家怎么吃</h3><p>{r.specialties?.join(' · ')}</p><dl><dt>地址与分店</dt><dd>{card.address} · {r.branch||'分店见来源'}</dd><dt>人均参考</dt><dd>{r.price_cny_per_person!=null?`约 ¥${r.price_cny_per_person}/人`:'待核'}<small>{r.price_basis}</small></dd><dt>营业</dt><dd>{r.opening||'暂未确认'}<small>采集日期 {r.checked_at||'未记录'}，请出发前再核对。</small></dd></dl><p>{r.level_reason}</p><details><summary>口碑与需要留意的事</summary><ul>{r.risks?.map((s,i)=><li key={i}>{s}</li>)}</ul><p>{r.xhs?.body_summary}</p><p>{r.xhs?.comments_summary}</p></details><div className="cc-source-links"><SourceLink href={r.dianping?.url}>大众点评</SourceLink><SourceLink href={r.gaode?.url}>高德地点</SourceLink></div></>}{card.kind==='spot'&&r.xhs_notes?.slice(0,3).map(n=><div className="cc-note" key={n.note_id}><SourceLink href={n.url}>{n.title}</SourceLink><p>{n.author}{n.date_visible?` · ${n.date_visible}`:''}</p>{n.body_summary&&<p>{n.body_summary}</p>}</div>)}<h3>照片与来源</h3><p>摄影：{card.photo?.author||'见原帖'} · 原图与水印保留</p><SourceLink href={card.source}>{card.sourceTitle||'照片原帖'}</SourceLink><p className="cc-muted">{card.sourceStatus||'打开原帖查看最新内容；入口可能需要 App 或登录。'}</p></div></div></dialog>
}
function RouteDiagram({groups}){const stops=routeStops(groups);if(!stops.length)return null;return <div className="cc-route-diagram" aria-label="收藏城市路线示意"><div className="cc-route-caption"><Compass size={19}/> 城市串联 · 示意路线</div><ol>{stops.map((name,i)=><li key={`${name}-${i}`}><span className="cc-stop-number">{i+1}</span><strong>{name}</strong><small>{i===0?'出发':i===stops.length-1&&name==='芜湖'?'回家':name==='淮安'?'途中备选':'收藏的一站'}</small>{i<stops.length-1&&<ArrowRight size={22}/>}</li>)}</ol><p>城市按去程、返程串联；市内为收藏清单，具体顺序请用导航确认。</p></div>}
export default function CardCollections({media,food,loading=false,active=true}){
 const cards=useMemo(()=>makeCards(media,food),[media,food]);
 const [choices,setChoices]=useState(readChoices),[storageFailed,setStorageFailed]=useState(false),[view,setView]=useState('collections'),[city,setCity]=useState('芜湖'),[kind,setKind]=useState('all'),[review,setReview]=useState('pending'),[cursor,setCursor]=useState(0),[preferredKey,setPreferredKey]=useState(''),[history,setHistory]=useState([]),[detail,setDetail]=useState(null),[message,setMessage]=useState(''),[dragX,setDragX]=useState(0),[exporting,setExporting]=useState(false),[progress,setProgress]=useState(''),[exportError,setExportError]=useState(''),[images,setImages]=useState([]);
 const gesture=useRef(null),exportsRef=useRef([]),mounted=useRef(true),rootRef=useRef(null),choicesRef=useRef(choices),deckHeading=useRef(null);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;exportsRef.current.forEach(p=>URL.revokeObjectURL(p.url))}},[]);
 useEffect(()=>{try{localStorage.setItem(COLLECTION_KEY,JSON.stringify(choices));setStorageFailed(false)}catch{setStorageFailed(true)}},[choices]);
 useEffect(()=>{exportsRef.current.forEach(p=>URL.revokeObjectURL(p.url));exportsRef.current=[];setImages([])},[choices]);
 useEffect(()=>{if(!active)setDetail(null);else {const frame=requestAnimationFrame(()=>{rootRef.current?.scrollIntoView({block:'start',behavior:'instant'})});return()=>cancelAnimationFrame(frame)}},[active,view,city]);
 choicesRef.current=choices;
 useEffect(()=>{setCursor(0)},[city,kind,review]);
 const liked=cards.filter(c=>choices[c.key]==='like'),seen=cards.filter(c=>choices[c.key]).length,groups=makeRoute(cards,choices);
 const pool=cards.filter(c=>c.city===city&&(kind==='all'||c.kind===kind));
 const queue=pool.filter(c=>review==='pending'?!choices[c.key]:choices[c.key]===review),current=queue.find(c=>c.key===preferredKey)||queue[(review==='pending'?0:cursor)%Math.max(1,queue.length)];
 function go(next){setView(next);setMessage('');setExportError('');gesture.current=null;setDragX(0)}
 function openCity(name){setPreferredKey('');setCity(name);setKind('all');setReview('pending');go('deck')}
 function vote(card,value){if(!card)return;setPreferredKey('');if(review===value)setCursor(i=>i+1);setHistory(h=>[...h.slice(-199),{key:card.key,old:choices[card.key],city:card.city}]);setChoices(c=>({...c,[card.key]:value}));setMessage(`${card.name} · ${value==='like'?'已喜欢':'已跳过'}`);setDragX(0)}
 function undo(){const last=history.at(-1);if(!last)return;setChoices(c=>{const n={...c};if(last.old)n[last.key]=last.old;else delete n[last.key];return n});setHistory(h=>h.slice(0,-1));setCity(last.city);setKind('all');setReview(last.old||'pending');setPreferredKey(last.key);setMessage('已撤销上一次选择');setDragX(0)}
 function remove(card){setHistory(h=>[...h,{key:card.key,old:choices[card.key],city:card.city}]);setChoices(c=>{const n={...c};delete n[card.key];return n});setMessage(`${card.name} 已放回未刷卡片`)}
 function pointerDown(e){if(e.button!==0||e.target.closest('button,a,details'))return;gesture.current={x:e.clientX,y:e.clientY,id:e.pointerId};e.currentTarget.setPointerCapture?.(e.pointerId)}
 function pointerMove(e){const g=gesture.current;if(!g||g.id!==e.pointerId)return;const dx=e.clientX-g.x,dy=e.clientY-g.y;if(Math.abs(dx)>Math.abs(dy)*1.2)setDragX(Math.max(-150,Math.min(150,dx)))}
 function pointerEnd(e){const g=gesture.current;gesture.current=null;setDragX(0);if(!g||g.id!==e.pointerId)return;const dx=e.clientX-g.x,dy=e.clientY-g.y;if(Math.abs(dx)>70&&Math.abs(dx)>Math.abs(dy)*1.3)vote(current,dx>0?'like':'dislike')}
 async function save(){if(exporting||!groups.length)return;setExporting(true);setExportError('');setProgress('正在整理照片与路线…');const snapshot=JSON.stringify(choices);try{const{exportCollection}=await import('./collection-export.js');const next=await exportCollection(groups,{base:B,onProgress:(n,total)=>{if(mounted.current)setProgress(`正在绘制 ${n} / ${total} 张卡片…`)}});if(!mounted.current||JSON.stringify(choicesRef.current)!==snapshot){if(mounted.current)setExportError('选择已更新，请重新生成长图。');next.forEach(p=>URL.revokeObjectURL(p.url));return}exportsRef.current.forEach(p=>URL.revokeObjectURL(p.url));exportsRef.current=next;setImages(next);setMessage(next.length>1?`已生成 ${next.length} 张长图，按完整卡片分段保存。`:'长图已生成，点击下方按钮保存。');}catch(e){if(mounted.current)setExportError(e.message||'生成失败，请重试')}finally{if(mounted.current){setExporting(false);setProgress('')}}}
 const countFor=(name,value)=>cards.filter(c=>c.city===name&&(!value||choices[c.key]===value)).length;
 return <section ref={rootRef} className="card-collections" aria-label="卡片集合"><header className="cc-topbar"><button className="cc-back" onClick={()=>go('collections')} disabled={view==='collections'}><ArrowLeft size={18}/> 城市集合</button><div className="cc-view-actions"><button aria-pressed={view==='liked'} onClick={()=>go('liked')}><Heart size={17} weight="fill"/> 已喜欢 {liked.length}</button><button className="cc-route-button" disabled={!liked.length} onClick={()=>go('result')}><Compass size={18}/> 生成我的路线</button></div></header>
 {storageFailed&&<p className="cc-warning" role="alert">浏览器未能保存选择，离开页面可能丢失。请先生成并保存攻略。</p>}
 {loading&&<p className="cc-muted" role="status">正在补齐美食卡片…</p>}
 {view==='collections'&&<><div className="cc-hero"><p className="cc-eyebrow">COLLECT A LITTLE SEA / 收藏一片海</p><h1>把喜欢的，<br/>留给这次旅行</h1><p>打开一座城市 · 左滑跳过，右滑喜欢<br/>让心动的风景和味道，成为你的海岸线。</p><div className="cc-total"><span>{cards.length} 张卡片</span><span>已刷 {seen} / {cards.length}</span><span><Heart weight="fill" size={15}/> 喜欢 {liked.length}</span></div></div><div className="cc-city-grid">{CITY_ORDER.map((name,i)=>{const cityCards=cards.filter(c=>c.city===name),n=cityCards.filter(c=>choices[c.key]).length,cover=cityCards.find(c=>c.kind==='spot'&&c.photo?.url)||cityCards[0];return <button className="cc-city-pack" key={name} onClick={()=>openCity(name)} disabled={!cityCards.length} aria-label={`打开${name}卡片集合`}><div className="cc-pack-title"><h2>{name}</h2><span>0{i+1}</span></div><p>{cityLines[name]}</p><Photo card={cover}/><div className="cc-pack-count"><span><MapPin size={15}/>景点 {cityCards.filter(c=>c.kind==='spot').length}</span><span><ForkKnife size={15}/>美食 {cityCards.filter(c=>c.kind==='food').length}</span></div><div className="cc-pack-progress"><progress value={n} max={Math.max(cityCards.length,1)}/><span>{n} / {cityCards.length}</span></div><div className="cc-pack-bottom">{n===cityCards.length?'已刷完 · 重新看看':n?'继续刷卡':'打开这一包'}<ArrowRight size={19}/></div></button>})}</div><p className="cc-footnote">全部景点与美食均可浏览；喜欢代表个人兴趣，原有待核说明会一起保留。选择保存在当前浏览器。</p></>}
 {view==='deck'&&<div className="cc-deck-layout"><aside className="cc-deck-sidebar"><p className="cc-eyebrow">ONE CITY, MANY LITTLE JOYS</p><h1 ref={deckHeading}>{city}</h1><p>{cityLines[city]}</p><div className="cc-city-switch" role="group" aria-label="切换卡片城市">{CITY_ORDER.map(name=><button key={name} aria-pressed={city===name} onClick={()=>openCity(name)}>{name}<span>{countFor(name,'like')} ♥</span></button>)}</div><div className="cc-deck-tip"><Heart size={24}/><p>不必每一站都去。<br/>先把真正喜欢的留下。</p></div></aside><div className="cc-deck-main"><div className="cc-deck-filters"><label>卡片类型<select aria-label="卡片类型" value={kind} onChange={e=>setKind(e.target.value)}><option value="all">景点 + 美食</option><option value="spot">只看景点</option><option value="food">只看美食</option></select></label><label>浏览范围<select aria-label="卡片浏览范围" value={review} onChange={e=>setReview(e.target.value)}><option value="pending">还没刷过</option><option value="like">已经喜欢</option><option value="dislike">已经跳过</option></select></label></div><div className="cc-deck-progress"><progress value={pool.filter(c=>choices[c.key]).length} max={Math.max(pool.length,1)}/><span>{pool.filter(c=>choices[c.key]).length} / {pool.length} 已刷</span></div>
 {current?<><div className="cc-stack"><article key={current.key} className={`cc-swipe-card ${dragX>35?'is-liking':dragX< -35?'is-skipping':''}`} tabIndex={0} aria-label={`${current.name}卡片，左右方向键选择`} onKeyDown={e=>{if(e.target!==e.currentTarget)return;if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();vote(current,e.key==='ArrowRight'?'like':'dislike')}}} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerEnd} onPointerCancel={()=>{gesture.current=null;setDragX(0)}} style={{transform:`translateX(${dragX}px) rotate(${dragX/22}deg)`}}><div className="cc-card-image"><Photo card={current}/><span className="cc-kind-stamp">{current.kind==='spot'?<MapPin size={15}/>:<ForkKnife size={15}/>} {kindLabel(current)}</span>{Math.abs(dragX)>35&&<span className="cc-vote-stamp">{dragX>0?'喜欢 ♥':'跳过 ×'}</span>}</div><div className="cc-card-copy"><p className="cc-eyebrow">{current.city}{current.kind==='food'&&current.raw.district?` / ${current.raw.district}`:''}</p><h2>{current.name}</h2><p className="cc-card-summary">{current.kind==='food'?(current.raw.specialties||[]).join(' · '):current.summary}</p>{current.kind==='food'&&<p className="cc-price">{current.raw.price_cny_per_person!=null?`约 ¥${current.raw.price_cny_per_person}/人`:'人均待核'} · {current.raw.level==='optional'?'顺路可选':current.raw.level==='exclude'?'暂不推荐':'先核对再去'}</p>}{current.warning&&<p className="cc-warning">{current.warning}</p>}<button className="cc-detail-button" onClick={()=>setDetail(current)}>查看详情 <ArrowRight size={17}/></button><small>摄影：{current.photo?.author||'见来源'} · 原图与水印保留</small></div></article></div><div className="cc-vote-actions"><button onClick={()=>vote(current,'dislike')} aria-label="不喜欢当前卡片"><span><X size={30}/></span>不喜欢</button><button onClick={undo} disabled={!history.length} aria-label="撤销上一次选择"><span><ArrowCounterClockwise size={24}/></span>撤销</button><button className="cc-like" onClick={()=>vote(current,'like')} aria-label="喜欢当前卡片"><span><Heart size={31} weight="fill"/></span>喜欢</button></div><p className="cc-swipe-hint">左滑跳过 · 右滑喜欢 · 也可以直接点按钮</p></>:<div className="cc-finished"><Check size={46}/><h2>{review==='pending'?'这一组刷完啦':'这一组没有卡片'}</h2><p>{review==='pending'?`你在${city}喜欢了 ${countFor(city,'like')} 张卡片。可以继续打开下一座城市。`:'换一个浏览范围，或看看其他城市。'}</p><button className="cc-primary" onClick={()=>openCity(CITY_ORDER[(CITY_ORDER.indexOf(city)+1)%CITY_ORDER.length])}>看看下一座城市 <ArrowRight size={18}/></button><button className="cc-detail-button" onClick={undo} disabled={!history.length}>撤销上一次选择</button></div>}
 </div></div>}
 {view==='liked'&&<><div className="cc-section-heading"><p className="cc-eyebrow">SAVED WITH A LITTLE HEART</p><h1>喜欢的，都在这里</h1><p>{liked.length} 张卡片。随时查看详情，也可以放回未刷列表。</p></div>{!liked.length&&<div className="cc-empty"><Heart size={42}/><p>还没有喜欢的卡片，去打开一包城市风景吧。</p><button className="cc-primary" onClick={()=>go('collections')}>去刷卡</button></div>}{groups.map(g=><section key={g.city} className="cc-saved-city"><h2>{g.city}<span>{g.items.length} 张</span></h2><div className="cc-saved-grid">{g.items.map(c=><article key={c.key}><button className="cc-saved-open" aria-label={`查看${c.name}详情`} onClick={()=>setDetail(c)}><Photo card={c}/><span>{kindLabel(c)} · {c.name}</span></button>{c.warning&&<p className="cc-warning">{c.warning}</p>}<button className="cc-text-button" onClick={()=>remove(c)}>放回未刷列表</button></article>)}</div></section>)}</>}
 {view==='result'&&<><div className="cc-section-heading cc-result-heading"><p className="cc-eyebrow">GOOD PLACES, YOUR OWN PACE</p><h1>我的海边路线 <Heart size={32}/></h1><p>把喜欢的地方，串成一段海风旅程。</p></div>{groups.length?<><RouteDiagram groups={groups}/><div className="cc-export-bar"><div><strong>{liked.filter(c=>c.kind==='spot').length} 个景点 · {liked.filter(c=>c.kind==='food').length} 家美食</strong><p>保留全部喜欢的卡片，不自动塞进原定的 5 / 6 天行程。</p></div><button className="cc-primary" disabled={exporting} onClick={save}><Download size={20}/>{exporting?'正在生成…':'保存攻略长图'}</button></div>{exporting&&<p role="status">{progress}</p>}{exportError&&<p className="cc-warning" role="alert">{exportError}</p>}{images.length>0&&<div className="cc-export-ready"><Check size={23}/><div><strong>攻略长图已准备好</strong><p>{images.length>1?`内容较多，已按完整卡片分成 ${images.length} 张长图，避免手机保存失败。`:'点击保存 PNG；手机也可打开图片后长按保存。'}</p><div>{images.map((im,i)=><a key={im.url} href={im.url} download={im.name}>保存{images.length>1?`第 ${i+1} 张`:''}长图 <Download size={16}/></a>)}</div>{images.map((im,i)=><details key={im.url}><summary>预览{images.length>1?`第 ${i+1} 张`:''}长图</summary><a href={im.url} target="_blank" rel="noopener noreferrer">打开原图</a><img src={im.url} alt={`已生成的攻略长图 ${i+1}`}/></details>)}</div></div>}{groups.map((g,i)=><section className="cc-route-city" key={g.city}><h2><span>{i+1}</span>{g.city}</h2>{g.city==='淮安'&&<p className="cc-warning">途中备选：只有你主动喜欢的淮安卡片才出现在这里。前往前需重新核对返程和住宿。</p>}{g.items.filter(c=>c.kind==='spot').length>4&&<p className="cc-warning">这一站选了较多景点，建议分天安排，不必一天走完。</p>}<div className="cc-route-columns">{['spot','food'].map(kind=><div key={kind}><h3>{kind==='spot'?<MapPin size={21}/>:<ForkKnife size={21}/>} {kind==='spot'?'想去的风景':'想吃的味道'}</h3>{g.items.filter(c=>c.kind===kind).length?g.items.filter(c=>c.kind===kind).map(c=><article className="cc-route-item" key={c.key}><button onClick={()=>setDetail(c)} aria-label={`查看${c.name}详情`}><Photo card={c}/></button><div><button className="cc-item-name" onClick={()=>setDetail(c)}>{c.name}<ArrowUpRight size={14}/></button><p>{kind==='food'?(c.raw.specialties||[]).join(' · '):c.summary}</p>{kind==='food'&&<p className="cc-muted">{c.address} · {c.raw.price_cny_per_person!=null?`约 ¥${c.raw.price_cny_per_person}/人`:'人均待核'}</p>}{c.warning&&<p className="cc-warning">{c.warning}</p>}<button className="cc-text-button" disabled={exporting} onClick={()=>remove(c)}>移出这份攻略</button></div></article>):<p className="cc-muted">这一类还没选，随时回卡片集合补充。</p>}</div>)}</div></section>)}</>:<div className="cc-empty"><p>还没有喜欢的卡片，先选几处心动的地方。</p><button className="cc-primary" onClick={()=>go('collections')}>去刷卡</button></div>}</>}
 <div className="cc-announcement" role="status" aria-live="polite">{message}</div>{detail&&<Details card={detail} onClose={()=>setDetail(null)}/>}
 </section>
}
