import {routeStops} from './collection-model.js';
const W=1080,MAX_HEIGHT=10000,HEADER=720,FOOTER=90;
const FONT='"PingFang SC","Microsoft YaHei",sans-serif';
export function wrapText(ctx,text,width){let out=[],line='';for(const ch of String(text||'')){if(ch==='\n'){out.push(line);line='';continue}if(ctx.measureText(line+ch).width>width&&line){out.push(line);line=ch}else line+=ch}if(line)out.push(line);return out;}
function textBlock(ctx,text,width,size=24,color='#43697d'){ctx.font=`${size}px ${FONT}`;return {lines:wrapText(ctx,text,width),size,color,height:wrapText(ctx,text,width).length*Math.ceil(size*1.5)}}
function paint(ctx,block,x,y){ctx.font=`${block.size}px ${FONT}`;ctx.fillStyle=block.color;ctx.textBaseline='top';for(const l of block.lines){ctx.fillText(l,x,y);y+=Math.ceil(block.size*1.5)}return y;}
function rect(ctx,x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.stroke()}}
function imageFor(url){return new Promise(resolve=>{if(!url){resolve(null);return}const im=new Image();let settled=false;const finish=value=>{if(settled)return;settled=true;clearTimeout(timer);resolve(value)};const timer=setTimeout(()=>finish(null),7000);im.onload=()=>finish(im);im.onerror=()=>finish(null);im.src=url;});}
function cardTexts(c){const r=c.raw;return [c.kind==='food'?(r.specialties||[]).join(' · '):c.summary,c.kind==='food'?`地址：${c.address}`:'',c.kind==='food'?`人均：${r.price_cny_per_person!=null?'约 ¥'+r.price_cny_per_person+'/人':'待核'} · 营业：${r.opening||'待核'}`:'',c.warning,c.kind==='food'?r.level_reason:'',`摄影：${c.photo?.author||'来源见原帖'} · 原图与水印保留`,`原帖：${c.sourceTitle||c.name}`,c.source||'来源待补'].filter(Boolean)}
// Canvas pages break only between whole cards; exported selections are never truncated.
export function layoutExport(groups,ctx){
 const blocks=groups.flatMap(g=>g.items.map(c=>{const title=textBlock(ctx,`${c.kind==='spot'?'景点':'美食'} · ${c.name}`,642,29,'#173f69');const texts=cardTexts(c).map(t=>textBlock(ctx,t,642,24,t===c.warning?'#a25540':'#43697d'));const height=Math.ceil(Math.max(330,48+title.height+16+texts.reduce((n,t)=>n+t.height+12,0)+22));return{c,city:g.city,title,texts,height}}));
 const pages=[];let blocksOnPage=[],h=HEADER,previous='';for(const block of blocks){let cityHeading=block.city!==previous;let extra=block.height+(cityHeading?84:0);if(h+extra+FOOTER>MAX_HEIGHT&&blocksOnPage.length){pages.push({blocks:blocksOnPage,height:h+FOOTER});blocksOnPage=[];h=HEADER;previous='';cityHeading=true;extra=block.height+84;}blocksOnPage.push({...block,cityHeading});h+=extra;previous=block.city;}if(blocksOnPage.length)pages.push({blocks:blocksOnPage,height:h+FOOTER});return pages;
}
function drawRoute(ctx,groups){const stops=routeStops(groups),cols=Math.min(4,stops.length),rows=Math.ceil(stops.length/cols);const pts=stops.map((name,i)=>{const row=Math.floor(i/cols),col=row%2?cols-1-i%cols:i%cols;return{name,x:140+col*(800/Math.max(1,cols-1)),y:320+row*110}});ctx.strokeStyle='#159cad';ctx.lineWidth=3;ctx.setLineDash([9,9]);ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.setLineDash([]);pts.forEach((p,i)=>{ctx.beginPath();ctx.arc(p.x,p.y,20,0,Math.PI*2);ctx.fillStyle=i===0||i===pts.length-1?'#fb7469':'#159cad';ctx.fill();ctx.fillStyle='white';ctx.font=`22px ${FONT}`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(String(i+1),p.x,p.y);ctx.font=`25px ${FONT}`;ctx.fillStyle='#173f69';ctx.fillText(p.name,p.x,p.y+43)});ctx.textAlign='left';return 320+rows*110;}
export async function exportCollection(groups,{base='/',onProgress=()=>{}}={}){
 if(!groups.length)throw Error('先喜欢几张卡片，再生成攻略');
 await document.fonts?.ready;const measure=document.createElement('canvas').getContext('2d');if(!measure)throw Error('设备暂时无法生成图片');const pages=layoutExport(groups,measure),decor=await imageFor(base+'assets/collections/coast-banner.png'),total=groups.reduce((n,g)=>n+g.items.length,0);const result=[];let done=0;
 try{for(let pi=0;pi<pages.length;pi++){const p=pages[pi],canvas=document.createElement('canvas');canvas.width=W;canvas.height=p.height;const ctx=canvas.getContext('2d');if(!ctx)throw Error('设备暂时无法生成图片');ctx.fillStyle='#fffdf6';ctx.fillRect(0,0,W,p.height);if(decor){ctx.save();ctx.globalAlpha=.62;ctx.drawImage(decor,0,0,W,620);ctx.restore()}rect(ctx,40,35,1000,640,24,'#fffffbcd','#8bcdd7');paint(ctx,textBlock(ctx,'海风来信 · 我的海边路线',940,43,'#173f69'),70,78);paint(ctx,textBlock(ctx,`收藏 ${total} 张卡片 · ${new Date().toLocaleDateString('zh-CN',{timeZone:'Asia/Shanghai'})} · ${pi+1}/${pages.length}`,940,23),72,154);paint(ctx,textBlock(ctx,'把喜欢的风景和味道，留给这次旅行。',940,25),72,208);drawRoute(ctx,groups);paint(ctx,textBlock(ctx,'城市串联示意，非导航或已预约行程。市内为收藏清单，请按时间和距离取舍；出发前核对营业、天气、预约与住宿。',935,23),72,555);let y=HEADER;
 for(const b of p.blocks){if(b.cityHeading){paint(ctx,textBlock(ctx,b.city+(b.city==='淮安'?' · 途中备选':''),940,35,'#173f69'),65,y+6);y+=84}rect(ctx,45,y,990,b.height-18,15,'#ffffff','#c1dee3');const im=await imageFor(b.c.photo?.url?base+b.c.photo.url:null);rect(ctx,64,y+24,235,270,9,'#eff8f7');if(im){const scale=Math.min(225/im.width,258/im.height);ctx.drawImage(im,69+(225-im.width*scale)/2,y+30+(258-im.height*scale)/2,im.width*scale,im.height*scale)}else paint(ctx,textBlock(ctx,'图片暂未载入\n请查看原帖',215,22),77,y+92);let ty=paint(ctx,b.title,325,y+24)+16;for(const t of b.texts)ty=paint(ctx,t,325,ty)+12;y+=b.height;onProgress(++done,total)}paint(ctx,textBlock(ctx,'原图与署名保留 · 私人旅行参考 · 海风来信',940,21),65,p.height-55);const blob=await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('图片生成失败，请稍后重试')),'image/png'));result.push({url:URL.createObjectURL(blob),name:`海风来信-我的攻略${pages.length>1?'-'+(pi+1):''}.png`});canvas.width=canvas.height=1;}return result;}catch(e){result.forEach(p=>URL.revokeObjectURL(p.url));throw e}
}
