import React,{useEffect,useRef,useState} from 'react';
import {X,ArrowLeft,ArrowRight,MagnifyingGlassPlus} from '@phosphor-icons/react';
import {safeExternal} from './utils.js';
import {albumImages,editorialFor,mediaUrl,useEditorial} from './editorial.js';
import './editorial-details.css';
function Source({url,children}){return safeExternal(url)?<a href={url} aria-label={typeof children==='string'?children:undefined} target="_blank" rel="noopener noreferrer">{children} ↗</a>:<span>{children} · 来源链接待补</span>}
export function OriginalImage({photo,className=''}){
 const [attempt,setAttempt]=useState(0),url=mediaUrl(photo?.url),fallback=mediaUrl(photo?.fallback_url);
 useEffect(()=>setAttempt(0),[url,fallback]);
 const activeUrl=attempt===0?url:attempt===1?fallback:'';
 return activeUrl?<img className={className} src={activeUrl} alt={photo.caption||photo.alt||'原帖实拍'} loading="lazy" referrerPolicy="no-referrer" draggable="false" onError={()=>setAttempt(a=>a===0&&fallback&&fallback!==url?1:2)}/>:<div className={`ed-image-error ${className}`} role="status">{url?'原图加载失败，请稍后重试或查看来源原帖。':'暂无可显示的原图。'}</div>;
}
export function SourceAlbum({card,entry}){
 const images=albumImages(card,entry),[source,setSource]=useState('all'),[index,setIndex]=useState(0),[zoom,setZoom]=useState(false),gesture=useRef(null),lightbox=useRef(null),zoomPrior=useRef(null);
 useEffect(()=>{if(!zoom)return;const previous=zoomPrior.current;lightbox.current?.querySelector('button')?.focus();return()=>previous?.focus?.()},[zoom]);
 const groups=[...new Map(images.map(p=>[p.source_id,p.source_name])).entries()];
 const shown=images.filter(p=>source==='all'||p.source_id===source),at=Math.min(index,Math.max(0,shown.length-1)),photo=shown[at];
 const move=n=>setIndex(i=>(i+n+shown.length)%Math.max(1,shown.length));
 useEffect(()=>{setSource('all');setIndex(0);setZoom(false)},[card.key]);
 return <section className="ed-album" aria-label={`${card.name}多来源相册`} onPointerDown={e=>{e.stopPropagation();gesture.current={x:e.clientX,y:e.clientY}}} onPointerUp={e=>{e.stopPropagation();const g=gesture.current;gesture.current=null;if(g&&!e.target.closest('button,a,select')&&Math.abs(e.clientX-g.x)>60&&Math.abs(e.clientX-g.x)>Math.abs(e.clientY-g.y)*1.5)move(e.clientX<g.x?1:-1)}} onPointerCancel={()=>{gesture.current=null}} onKeyDown={e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){if(e.target.closest('select'))return;e.stopPropagation();e.preventDefault();move(e.key==='ArrowRight'?1:-1)}}}>
 <h3>实拍相册 · {images.length} 张</h3><label className="ed-source-filter">照片来源<select aria-label="筛选照片来源" value={source} onChange={e=>{setSource(e.target.value);setIndex(0)}}><option value="all">全部来源 · {images.length} 张</option>{groups.map(([id,name])=><option key={id} value={id}>{name} · {images.filter(p=>p.source_id===id).length} 张</option>)}</select></label>
 {photo?<><div className="ed-album-stage"><OriginalImage photo={photo}/><button className="ed-enlarge" aria-label="放大查看原图" onClick={()=>{zoomPrior.current=document.activeElement;setZoom(true)}}><MagnifyingGlassPlus size={20}/> 放大</button></div><div className="ed-album-controls"><button aria-label="上一张照片" disabled={shown.length<2} onClick={()=>move(-1)}><ArrowLeft size={20}/><span>上一张</span></button><span role="status">{at+1} / {shown.length}{source!=='all'?` · 总共 ${images.length} 张`:''}</span><button aria-label="下一张照片" disabled={shown.length<2} onClick={()=>move(1)}><span>下一张</span><ArrowRight size={20}/></button></div><div className="ed-photo-credit"><p>{photo.caption}</p><p>摄影：{photo.author} · {photo.source_name}</p><Source url={photo.source_url}>照片原帖</Source>{photo.license&&<small>{photo.source_name} · <Source url={photo.license_url}>{photo.license}</Source> · {photo.changes||'见原图来源许可'}</small>}<small>图片完整显示，水印保留；部分点评图片为网页预览尺寸。历史影像不代表当前客流、天气或营业。</small></div><div className="ed-thumbnails" aria-label="照片缩略图">{shown.map((p,i)=><button key={p.url} aria-label={`查看第 ${i+1} 张照片`} aria-pressed={i===at} onClick={()=>setIndex(i)}><OriginalImage photo={p}/><span>{i+1}</span></button>)}</div></>:<p role="status">此条记录尚无可显示的原图。</p>}
 {zoom&&photo&&<div className="ed-lightbox" ref={lightbox} role="dialog" aria-modal="true" aria-label="原图放大查看" tabIndex={-1} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();setZoom(false)}if(e.key==='Tab'){const nodes=[...e.currentTarget.querySelectorAll('button,a[href]')],first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}}} onClick={e=>{if(e.target===e.currentTarget)setZoom(false)}}><button autoFocus aria-label="关闭放大查看" onClick={()=>setZoom(false)}><X size={24}/></button><OriginalImage photo={photo}/><p>摄影：{photo.author} · <Source url={photo.source_url}>{photo.source_name}</Source></p></div>}
 </section>;
}
function Paragraphs({value}){return (Array.isArray(value)?value:[value]).filter(Boolean).map((p,i)=><p key={i}>{typeof p==='string'?p:JSON.stringify(p)}</p>)}
function Items({title,items}){return items?.length?<section><h3>{title}</h3><ul>{items.map((p,i)=><li key={i}>{p}</li>)}</ul></section>:null}
export default function EditorialDetails({card,onClose}){
 const data=useEditorial(),entry=editorialFor(data,card),r=card.raw||{},ref=useRef(null);
 useEffect(()=>{const d=ref.current,previous=document.activeElement,overflow=document.body.style.overflow;document.body.style.overflow='hidden';if(d.showModal)d.showModal();else d.setAttribute('open','');const escape=e=>{if(e.key==='Escape'&&!e.defaultPrevented&&!e.target.closest('.ed-lightbox'))onClose()};d.addEventListener('keydown',escape);return()=>{d.removeEventListener('keydown',escape);d.close?.();document.body.style.overflow=overflow;previous?.focus?.()}},[card.key]);
 const overview=entry?.overview?.length?entry.overview:[card.summary,...(card.kind==='spot'?(r.xhs_notes||[]).map(n=>n.body_summary):[r.xhs?.body_summary])].filter(Boolean);
 const sources=entry?.sources?.length?entry.sources:card.kind==='food'?[{platform:'小红书',title:r.xhs?.title,author:r.xhs?.author,url:r.xhs?.url,read_scope:r.xhs?.canonical_status},{platform:'大众点评',title:r.branch||card.name,url:r.dianping?.url,read_scope:r.dianping?.status},{platform:'高德',title:card.name,url:r.gaode?.url,read_scope:r.gaode?.status}]: (r.xhs_notes||[]).map(n=>({platform:'小红书',title:n.title,author:n.author,url:n.url,read_scope:n.link_status_label}));
 return <dialog className="ed-dialog" ref={ref} aria-label={`${card.name}详情`} onCancel={e=>{e.preventDefault();onClose()}} onClick={e=>{if(e.target===e.currentTarget)onClose()}}><button className="ed-close" aria-label="关闭详情" onClick={onClose}><X size={24}/></button><div className="ed-body"><p className="eyebrow">{card.city} / {card.kind==='food'?'美食':'景点'}</p><h2>{card.name}</h2><nav className="ed-jump-links" aria-label="详情阅读位置"><button onClick={()=>ref.current?.querySelector('.ed-album')?.scrollIntoView({block:'start',behavior:'smooth'})}>看全部照片</button><button onClick={()=>ref.current?.querySelector('.ed-review')?.scrollIntoView({block:'start',behavior:'smooth'})}>看口碑分析</button></nav><section aria-label="综合介绍"><h3>综合介绍</h3><Paragraphs value={overview}/></section>{card.warning&&<p className="ed-caution">{card.warning}</p>}<Items title={card.kind==='food'?'这家吃什么':'值得看的地方'} items={entry?.highlights}/><SourceAlbum card={card} entry={entry}/><section className="ed-review"><h3>小红书经验分析</h3><Paragraphs value={entry?.review_summary?.xiaohongshu||r.xhs?.comments_summary||r.xhs?.body_summary||(card.kind==='spot'?'已采集原帖介绍与影像；独立评论和近期情况未完整核对。':'尚无完整评论分析。')}/><h3>大众点评口碑分析</h3><Paragraphs value={entry?.review_summary?.dianping||r.dianping?.summary||'尚无此条记录的完整大众点评口碑核验，不能据此判断近期评分或客流。'}/><Paragraphs value={entry?.review_summary?.coverage||r.dianping?.recent_negative_review_scope}/></section><Items title="实际怎么安排" items={entry?.practical}/>{card.kind==='food'&&<section><h3>到店信息</h3><p>特色：{r.specialties?.join(' · ')||'待核'}</p><p>地址 / 分店：{card.address} · {r.branch||'分店待核'}</p><p>人均参考：{r.price_cny_per_person!=null?`约 ¥${r.price_cny_per_person}/人`:'待核'} · {r.price_basis||'非当前价格保证'}</p><p>营业：<span>{r.opening||'暂未确认'}</span> · 出发前再核对</p><Paragraphs value={r.level_reason}/></section>}<Items title="需要留意的具体风险" items={entry?.cautions?.length?entry.cautions:r.risks?.length?r.risks:[card.warning||'出发前核对天气、开放时间、停车与现场情况。']}/><section className="ed-sources"><h3>资料来源与读取范围</h3>{sources.map((s,i)=><div key={`${s.url}-${i}`}><strong>{s.platform||s.source_name||'来源'}</strong><Source url={s.url}>{s.title||'查看来源'}</Source>{s.author&&<p>作者：{s.author}</p>}<Paragraphs value={s.read_scope||'读取范围未记录，请按现有资料边界使用。'}/></div>)}{entry&&<small>整理日期：{data.updated_at||'见资料记录'}</small>}</section></div></dialog>;
}
