import React,{useEffect,useState} from 'react';
import {safeExternal} from './utils.js';
import './food-guide.css';
const B=import.meta.env.BASE_URL;
const categories={snack:'当地小吃',meal:'本地正餐',dessert:'特色甜品'};
const levels={must:'值得专程去',optional:'顺路可选',caution:'先核对再去',exclude:'暂不推荐'};
function Link({href,children}){return safeExternal(href)?<a href={href} target="_blank" rel="noopener noreferrer">{children} ↗</a>:<span>{children}：链接待补</span>}
function Evidence({entry:e}){return <details className="food-evidence"><summary>查看依据</summary><p><strong>等级理由：</strong>{e.level_reason||'证据仍待补充'}</p><p><strong>原帖正文：</strong>{e.xhs?.body_summary||'未记录'}</p><p><strong>评论摘读：</strong>{e.xhs?.comments_summary||'未记录'}</p><p><strong>作者与评论人：</strong>{e.xhs?.author_risk||'作者背景未知'}；{e.xhs?.commenter_check||'评论人背景未知'}</p><p><strong>店名反查：</strong>{e.xhs?.reverse_search||'未记录'}</p><p><strong>点评可见范围：</strong>{e.dianping?.summary||'未读取'}；{e.dianping?.recent_negative_review_scope||'近期差评未核'}</p><p><strong>位置与营业：</strong>{e.gaode?.summary||'未核'}；{e.opening||'营业时间未知'}{e.opening_checked?'（已记录核验，请出发前再查）':'（营业未确认）'}</p><p><strong>分店匹配：</strong>{e.dianping?.matched_branch?'点评分店已匹配':'点评分店尚未确认'} · {e.address||'详细地址待核'}</p><p>资料日期：{e.checked_at||'未记录'} · {e.status==='complete'?'采集记录齐全；口碑和营业按上述边界使用':'候选资料仍有待补充'}</p>{e.photo?.visual_evidence&&<p>图片匹配依据：{e.photo.visual_evidence}</p>}{e.xhs?.additional_posts?.length>0&&<p>补充帖子：{e.xhs.additional_posts.map((p,i)=>typeof p==='string'?<Link key={i} href={p}>原帖 {i+1}</Link>:<Link key={i} href={p.url}>{p.title||`原帖 ${i+1}`}</Link>)}</p>}</details>}
export default function FoodGuide({data,loading,activeCity,day,activeDay,full=false,expanded,onExpanded,id="food-guide",scopeToCity=false,onBrowseAll}){
 const [city,setCity]=useState(activeCity),[category,setCategory]=useState('全部'),[level,setLevel]=useState('推荐候选');
 useEffect(()=>{setCity(activeCity)},[activeCity]);
 const selectedCity=scopeToCity?activeCity:city;
 const entries=Array.isArray(data.entries)?data.entries:[],targets=data.targets||{},names=[...new Set([...(data.cities||Object.keys(targets)),...entries.map(e=>e.city),'青岛','威海','连云港','日照','芜湖','淮安'])];
 const targetTotal=Object.values(targets).reduce((n,v)=>n+(Number(v)||0),0);
 const count=entries.filter(e=>e.status==='complete').length;
 const recommended=entries.filter(e=>['must','optional'].includes(e.level)).length,caution=entries.filter(e=>e.level==='caution').length,excluded=entries.filter(e=>e.level==='exclude').length;
 const shown=entries.filter(e=>(selectedCity==='全部'||e.city===selectedCity)&&(category==='全部'||e.category===category)&&(level==='全部'||level==='推荐候选'&&e.level!=='exclude'||e.level===level)).sort((a,b)=>Number(!!b.local_character)-Number(!!a.local_character)||(['must','optional','caution','exclude'].indexOf(a.level)-['must','optional','caution','exclude'].indexOf(b.level))||a.name.localeCompare(b.name,'zh-CN'));
 const Shell=full?'div':'details',Heading=full?'div':'summary';
 return <section id={id} className={`food-guide ${scopeToCity?'is-day-food':''}`} aria-label="按城市查看美食图文库"><Shell {...(full?{}:{open:expanded,onToggle:e=>{if(e.currentTarget.open!==expanded)onExpanded(e.currentTarget.open)}})}><Heading className="food-guide-heading"><span><small>FOOD NOTEBOOK</small><strong>这一站吃什么</strong><span>第 {activeDay+1} 天 · {day?.sleep||activeCity} · 先看当地特色</span></span><span className="food-summary-count">{count} 家图文{targetTotal?` / 补采目标 ${targetTotal}`:''}<span className="food-expand-hint">{full?'图文与来源':expanded?'收起美食图文':'展开美食图文库'}</span></span></Heading><div className="food-body"><p className="food-intro">按当天所在城市找吃的，也可以自由翻其他城市。这里的店铺是用餐候选，不会自动添加到每日路线。默认优先有地方特色依据的记录；“暂不推荐”单独筛选查看。</p><p className="food-progress" role="status">{loading?'正在载入美食资料…':`已采集 ${count} 家图文：${recommended} 家顺路可选、${caution} 家需先核对、${excluded} 家暂不推荐${targetTotal?`。其余五城补采目标 ${targetTotal} 家，暂不推荐不计入达标数量，芜湖仅作出发参考`:''}。`}{data.updated_at&&` 更新：${String(data.updated_at).slice(0,10)}`}</p><div className="food-city-progress">{names.map(name=><span key={name}>{name} · {entries.filter(e=>e.city===name&&['must','optional'].includes(e.level)).length} 可选 · {entries.filter(e=>e.city===name&&e.level==='caution').length} 待核 · {entries.filter(e=>e.city===name).length} 图文{targets[name]?` / 目标 ${targets[name]}`:data.city_notes?.[name]?` · ${data.city_notes[name]}`:''}</span>)}</div><div className="food-filters">{!scopeToCity&&<label>城市<select aria-label="美食城市" value={city||'全部'} onChange={e=>setCity(e.target.value)}><option>全部</option>{[...new Set([...names,activeCity].filter(Boolean))].map(name=><option key={name}>{name}</option>)}</select></label>}<label>想吃什么<select aria-label="美食类别" value={category} onChange={e=>setCategory(e.target.value)}><option>全部</option>{Object.entries(categories).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>推荐边界<select aria-label="美食推荐等级" value={level} onChange={e=>setLevel(e.target.value)}><option>推荐候选</option>{Object.entries(levels).map(([id,label])=><option key={id} value={id}>{label}</option>)}<option>全部</option></select></label></div><p className="food-result-count" aria-live="polite">{selectedCity||'全部'} · 找到 {shown.length} 家{level==='exclude'?'暂不推荐的记录':level==='全部'?'采集记录（含暂不推荐）':'候选'}</p>{!loading&&!shown.length&&<div className="food-empty"><h3>{entries.length?'这一组还没有合适的记录':'美食图文正在逐家采集'}</h3><p>{entries.length?'换一个城市或类别继续翻看，当前城市暂不填入未经采集的店。':'原图、专帖和平台实测资料整理好后，才会显示在这里。目标不是已完成数量；芜湖半天出发中转，已暂停补采。'}</p>{entries.length>0&&<button className="secondary" onClick={()=>{if(scopeToCity){onBrowseAll?.();return;}setCity('全部');setCategory('全部');setLevel('全部')}}>{scopeToCity?'去全部美食资料中找':'查看全部采集记录（含暂不推荐）'}</button>}</div>}<div className="food-grid">{shown.map(e=><article key={e.id} className={`food-card food-level-${e.level}`}>
 {e.photo?.url&&<img className="food-photo" src={`${B}${e.photo.url}`} alt={e.photo.alt||`${e.name} · 小红书原帖实拍`} width={e.photo.width} height={e.photo.height} loading="lazy"/>}<div className="food-card-body"><div className="food-tags"><span>{categories[e.category]||'用餐候选'}</span><span>{levels[e.level]||'证据待补'}</span></div><h3>{e.name}</h3><p className="food-specialties">{(e.specialties||[]).join(' · ')||'具体菜品待核'}</p><p className="food-quick-price"><span>{e.city} · {e.district||'区域待核'}</span><span>{e.price_cny_per_person!=null?`约 ¥${e.price_cny_per_person}/人`:'人均待核'}</span></p><p className="food-why">{e.why||'推荐理由待补'}</p><p className="food-photo-credit">摄影：{e.photo?.author||e.xhs?.author||'待记录'} · 原图与水印保留</p><div className="food-main-links"><Link href={e.xhs?.url}>小红书原帖</Link><Link href={e.dianping?.url}>{e.dianping?.kind==='shop'?'大众点评门店':'点评搜索 · 分店待核'}</Link></div><p className="food-post-title">原帖：{e.xhs?.title}</p><p className="food-access-status">{e.xhs?.canonical_readable?'原帖入口本轮可读，请留意访问状态变化':'小红书直链本轮不可读，请在 App 按上方标题与作者搜索。'}{!e.dianping?.readable&&' 点评入口本轮未能打开。'}</p><details className="food-details"><summary>地址、营业与核验依据</summary><p><strong>原帖：</strong>{e.xhs?.title} · {e.xhs?.author}</p><p><strong>地址 / 分店：</strong>{e.address||'地址待核'} · {e.branch||'分店待核'}</p><p><strong>营业：</strong>{e.opening||'当前营业未确认'}{!e.opening_checked&&' · 出发前需核对'}</p><p><strong>适合：</strong>{(e.scene||[]).join(' / ')}</p>{e.local_character&&<p>当地特色：{e.local_character}</p>}<p><strong>人均依据：</strong>{e.price_basis||'价格来源未知'} · 非当前报价保证</p><p className="food-risk"><strong>需要留意：</strong>{e.risks?.length?e.risks.join('；'):'当前营业、食材和排队仍需出发前核对。'}</p><div className="food-links"><div><Link href={e.xhs?.url}>小红书单篇原帖 · {e.xhs?.title} · {e.xhs?.author}</Link><small>{e.xhs?.canonical_status}</small></div><div><Link href={e.dianping?.url}>{e.dianping?.kind==='shop'?'大众点评 · 门店':'大众点评 · 搜索备选（分店未核）'}</Link><small>{e.dianping?.status}</small></div><div><Link href={e.gaode?.url}>{e.gaode?.kind==='place'?'高德 · 地点补充':'高德 · 地点搜索（待匹配）'}</Link><small>{e.gaode?.status}</small></div></div><Evidence entry={e}/></details></div></article>)}</div></div></Shell></section>
}
