import React,{useEffect,useRef,useState} from 'react';
import './landmark-map.css';
import {Car,Compass,ArrowLeft,ArrowRight,ArrowCounterClockwise,Pause,Play,MapTrifold} from '@phosphor-icons/react';

const points={huaian:[13,66],wuhu:[18,83],lianyungang:[33,64],rizhao:[48,47],qingdao:[62,31],weihai:[83,15]};
export function FlatRoute({cities,activeCity,onCity,destination,origin='wuhu',motion}){
 const p=points[destination]||points.wuhu,start=points[origin]||points.wuhu;
 return <div className="flat-route" aria-label="可点击的二维跨城路线示意图">
  <svg viewBox="0 0 600 400" preserveAspectRatio="none" aria-hidden="true"><defs><marker id="route-direction" markerWidth="6" markerHeight="6" refX="4" refY="3" orient="auto"><path d="M0 0L6 3L0 6Z" fill="#b95e3e"/></marker></defs><path d="M600 0H495L458 83 389 100 342 154 309 195 252 238 212 307 235 400H600Z" fill="#c7dedc"/><path d="M108 332L198 256 372 124 498 60" className="route-out"/><path d="M498 60L288 188 108 332" className="route-home"/>{origin!==destination&&<path d={`M${start[0]*6} ${start[1]*4}L${p[0]*6} ${p[1]*4}`} className="route-active" markerEnd="url(#route-direction)"/>}<text x="410" y="290">黄海</text><text x="43" y="369">长江 · 内陆起点</text></svg>
  <span className="flat-route-key"><i/>去程 <i/>返程 · 线形不代表实际道路</span>
  {cities.map(c=><button key={c.id} className={`flat-city ${activeCity===c.id?'selected':''}`} style={{left:`${points[c.id][0]}%`,top:`${points[c.id][1]}%`}} aria-label={`地图城市：${c.name}`} aria-pressed={activeCity===c.id} onClick={()=>onCity(c.id)}><span/>{c.name}</button>)}
  <span key={`${origin}-${destination}`} className={`flat-car ${motion?'animate':''}`} style={{left:`${p[0]}%`,top:`${p[1]}%`,'--start-x':`${start[0]}%`,'--start-y':`${start[1]}%`}} aria-label={`小车位于${cities.find(c=>c.id===destination)?.name||'芜湖'}`}><Car weight="fill" size={26}/></span>
 </div>
}
export default function RouteMap({sceneRoot,scene,sceneError,sceneReady,viewMode,setViewMode,flat,setFlat,reducedMotion,motion,setMotion,cities,city,activeCity,onCity,itinerary,activeDay,chooseDay,days,chooseDays,scrollPlan}){
 const canvasRoot=useRef(null),zoomRef=useRef(1);
 const [zoom,setZoom]=useState(1);
 function changeZoom(value){const next=Math.max(.75,Math.min(3,value));zoomRef.current=next;setZoom(next);scene.current?.setZoom?.(next)}
 useEffect(()=>{if(sceneReady)scene.current?.setZoom?.(zoomRef.current)},[sceneReady]);
 useEffect(()=>{const root=canvasRoot.current;if(!root)return;let pinch=null;const distance=t=>Math.hypot(t[0].clientX-t[1].clientX,t[0].clientY-t[1].clientY);function wheel(e){e.preventDefault();changeZoom(zoomRef.current*Math.exp(-Math.max(-120,Math.min(120,e.deltaY*(e.deltaMode===1?16:1)))*.003))}function start(e){if(e.touches.length===2&&Array.from(e.touches).every(t=>root.contains(t.target))){pinch={distance:distance(e.touches),zoom:zoomRef.current};if(e.cancelable)e.preventDefault()}}function move(e){if(pinch&&e.touches.length===2){if(e.cancelable)e.preventDefault();changeZoom(pinch.zoom*distance(e.touches)/Math.max(1,pinch.distance))}}function end(){pinch=null}root.addEventListener('wheel',wheel,{passive:false});root.addEventListener('touchstart',start,{passive:false});root.addEventListener('touchmove',move,{passive:false});root.addEventListener('touchend',end);root.addEventListener('touchcancel',end);return()=>{root.removeEventListener('wheel',wheel);root.removeEventListener('touchstart',start);root.removeEventListener('touchmove',move);root.removeEventListener('touchend',end);root.removeEventListener('touchcancel',end)}},[]);
 const [landmarks,setLandmarks]=useState([]),[selectedLandmark,setSelectedLandmark]=useState('');
 useEffect(()=>{if(sceneReady)setLandmarks(scene.current?.getLandmarks?.()||[])},[sceneReady]);
 useEffect(()=>setSelectedLandmark(''),[activeCity]);
 useEffect(()=>{const root=sceneRoot.current;if(!root)return;function select(e){setSelectedLandmark(e.detail.id);setViewMode('immersive')}root.addEventListener('landmarkselect',select);return()=>root.removeEventListener('landmarkselect',select)},[sceneRoot,setViewMode]);
 const focused=landmarks.find(item=>item.id===selectedLandmark);
 function chooseLandmark(id){setSelectedLandmark(id);if(id){scene.current?.focusLandmark?.(id);setViewMode('immersive')}else scene.current?.clearLandmark?.()}
 const day=itinerary.days[activeDay];const destination=cities.find(c=>c.name===day.sleep)?.id||'wuhu';const origin=activeDay===0?'wuhu':cities.find(c=>c.name===itinerary.days[activeDay-1].sleep)?.id||'wuhu';const useFlat=flat||sceneError;
 return <section className="route-first" aria-label="全程路线地图">
  <div className="route-world">
   <div className="world-topline"><span><Compass size={17}/><span className="map-instructions">{useFlat?'点击选城市，滚轮或双指缩放':viewMode==='immersive'?(focused?'拖动看景点，滚轮或双指缩放':'拖动看城市，滚轮或双指缩放'):'拖动旋转，滚轮或双指缩放'}<small>城市位置为示意，请用导航确认路线 · 芜湖为长江内陆起点{reducedMotion?' · 减少动态':''}</small></span></span></div>
   <div className="route-canvas" ref={canvasRoot} style={{'--map-zoom':zoom}}><div ref={sceneRoot} className={`scene ${useFlat?'scene-hidden':''}`} style={{position:'absolute'}} aria-hidden={useFlat} aria-label="芜湖至山东海岸的三维路线示意图"/>{useFlat&&<FlatRoute cities={cities} activeCity={activeCity} onCity={onCity} destination={destination} origin={origin} motion={motion}/>}{!sceneReady&&!sceneError&&!flat&&<div className="scene-loading"><Compass size={28}/><span>正在打开地图…</span><button className="secondary" onClick={()=>setFlat(true)}>先看 2D 路线</button></div>}

   <div className="map-zoom-controls" role="group" aria-label="地图缩放"><button aria-label="放大地图" disabled={zoom>=3} onClick={()=>changeZoom(zoomRef.current*1.25)}>＋</button><button aria-label="恢复地图原始大小" onClick={()=>changeZoom(1)}>{Math.round(zoom*100)}%</button><button aria-label="缩小地图" disabled={zoom<=.75} onClick={()=>changeZoom(zoomRef.current/1.25)}>−</button></div>
   </div>
  </div>
  <div className="map-city-switcher" role="group" aria-label="选择地图城市">{cities.map(c=><button key={c.id} aria-pressed={activeCity===c.id} onClick={()=>onCity(c.id)}>{c.name}</button>)}</div>
  {!useFlat&&landmarks.length>0&&<div className="landmark-explorer"><label><span>近看一个景点</span><select aria-label="选择要近看的景点" value={selectedLandmark} onChange={e=>chooseLandmark(e.target.value)}><option value="">{city.name}全景</option><optgroup label={city.name}>{landmarks.filter(item=>item.city===activeCity).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</optgroup>{focused&&focused.city!==activeCity&&focused.city!=='huaian'&&<option value={focused.id}>{focused.name}</option>}{activeCity!=='huaian'&&<optgroup label="淮安 · 途中备选">{landmarks.filter(item=>item.city==='huaian').map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</optgroup>}</select></label>{focused&&<div className="landmark-caption"><span>{focused.name}{focused.optional&&!itinerary.days.some(d=>d.sleep==='淮安')?' · 途中备选，不改变行程':''}</span><button onClick={()=>chooseLandmark('')}>返回城市全景</button></div>}<p>地图中的模型可以点开看；造型为简化示意，实景请看景点照片。</p></div>}
  <details className="journey-map-tools"><summary>视角与地图工具</summary><div className="journey-tool-buttons"><button className="secondary" onClick={()=>setFlat(!useFlat)} disabled={sceneError} aria-pressed={useFlat}><MapTrifold size={17}/>{sceneError?'2D 模式':useFlat?'切换 3D':'切换 2D'}</button>{!useFlat&&<><button className="secondary" aria-label="向左旋转地图" onClick={()=>scene.current?.rotate(-1)}><ArrowLeft size={18}/>向左旋转</button><button className="secondary" aria-label="向右旋转地图" onClick={()=>scene.current?.rotate(1)}><ArrowRight size={18}/>向右旋转</button><button className="secondary" aria-label="重置三维视角" onClick={()=>scene.current?.reset()}><ArrowCounterClockwise size={18}/>重置视角</button></>}<button className="secondary" disabled={reducedMotion} aria-label={reducedMotion?'遵循系统减少动态设置':motion?'暂停三维动态':'开启三维动态'} aria-pressed={!motion} onClick={()=>setMotion(v=>!v)}>{motion?<Pause size={18}/>:<Play size={18}/>} {motion?'暂停动态':'开启动态'}</button><button className="secondary" aria-pressed={viewMode==='overview'} onClick={()=>{setSelectedLandmark('');setViewMode('overview')}}>查看全程</button><button className="secondary" aria-pressed={viewMode==='immersive'} disabled={useFlat} onClick={()=>{setSelectedLandmark('');scene.current?.clearLandmark?.();setViewMode('immersive')}}>近看城市</button></div></details>
  <p className="map-caption">城市位置为示意，请用导航确认路线 · 芜湖在内陆长江边{sceneError?' · 设备不支持 WebGL，已切至可点 2D 路线':''}</p>
 </section>
}
